### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AssassinAguilar** [abuanwar072/Responsive-and-Animated-Portfolio-Flutter#1]
Well not an issue but a suggestion after completing your code in vs code open terminal and write ```flutter build web --web-renderer html``` then push your code to github so your flutter code get a github page to check the output at https://abuanwar027.github.io/Responsive-and-Animated-Portfolio-Flutter/build/web/ rather than going to YouTube and check the output

**Comment by abuanwar072** [comment]
> Well not an issue but a suggestion after completing your code in vs code open terminal and write `flutter build web --web-renderer html` then push your code to github so your flutter code get a github page to check the output at https://abuanwar027.github.io/Responsive-and-Animated-Portfolio-Flutter/build/web/ rather than going to YouTube and check the output

Live preview added

**Comment by mrdc** [comment]
@abuanwar072 
> Live preview added

Hi, thanks! 
One small question: I see the loading indicator prior main app execution, but I don't see any related code for it in html, which is quite strange :)
